spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
          - id: employee-service
            uri: lb://employee-service
            predicates:
              - Path=/api/employee/**
              - Method=GET
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/

